const List<String> kList = [
  "ALL",
  "XCD",
  "EUR",
  "BBD",
  "BTN",
  "BND",
  "XAF",
  "CUP",
  "USD",
  "FKP",
  "GIP",
  "HUF",
  "IRR",
  "JMD",
  "AUD",
  "LAK",
  "LYD",
  "MKD",
  "XOF",
  "NZD",
  "OMR",
  "PGK",
  "RWF",
  "WST",
  "RSD",
  "SEK",
  "TZS",
  "AMD",
  "BSD",
  "BAM",
  "CVE",
  "CNY",
  "CRC",
  "CZK",
  "ERN",
  "GEL",
  "HTG",
  "INR",
  "JOD",
  "KRW",
  "LBP",
  "MWK",
  "MRO",
  "MZN",
  "ANG",
  "PEN",
  "QAR",
  "STD",
  "SLL",
  "SOS",
  "SDG",
  "SYP",
  "AOA",
  "AWG",
  "BHD",
  "BZD",
  "BWP",
  "BIF",
  "KYD",
  "COP",
  "DKK",
  "GTQ",
  "HNL",
  "IDR",
  "ILS",
  "KZT",
  "KWD",
  "LSL",
  "MYR",
  "MUR",
  "MNT",
  "MMK",
  "NGN",
  "PAB",
  "PHP",
  "RON",
  "SAR",
  "SGD",
  "ZAR",
  "SRD",
  "TWD",
  "TOP",
  "VEF",
  "DZD",
  "ARS",
  "AZN",
  "BYR",
  "BOB",
  "BGN",
  "CAD",
  "CLP",
  "CDF",
  "DOP",
  "FJD",
  "GMD",
  "GYD",
  "ISK",
  "IQD",
  "JPY",
  "KPW",
  "LVL",
  "CHF",
  "MGA",
  "MDL",
  "MAD",
  "NPR",
  "NIO",
  "PKR",
  "PYG",
  "SHP",
  "SCR",
  "SBD",
  "LKR",
  "THB",
  "TRY",
  "AED",
  "VUV",
  "YER",
  "AFN",
  "BDT",
  "BRL",
  "KHR",
  "KMF",
  "HRK",
  "DJF",
  "EGP",
  "ETB",
  "XPF",
  "GHS",
  "GNF",
  "HKD",
  "XDR",
  "KES",
  "KGS",
  "LRD",
  "MOP",
  "MVR",
  "MXN",
  "NAD",
  "NOK",
  "PLN",
  "RUB",
  "SZL",
  "TJS",
  "TTD",
  "UGX",
  "UYU",
  "VND",
  "TND",
  "UAH",
  "UZS",
  "TMT",
  "GBP",
  "ZMW",
  "BTC",
  "BYN",
  "BMD",
  "GGP",
  "CLF",
  "CUC",
  "IMP",
  "JEP",
  "SVC",
  "ZMK",
  "XAG",
  "ZWL",
];

const List<String> kcurrencies = [
  "Albanian Lek",
  "East Caribbean Dollar",
  "Euro",
  "Barbadian Dollar",
  "Bhutanese Ngultrum",
  "Brunei Dollar",
  "Central African CFA Franc",
  "Cuban Peso",
  "United States Dollar",
  "Falkland Islands Pound",
  "Gibraltar Pound",
  "Hungarian Forint",
  "Iranian Rial",
  "Jamaican Dollar",
  "Australian Dollar",
  "Lao Kip",
  "Libyan Dinar",
  "Macedonian Denar",
  "West African CFA Franc",
  "New Zealand Dollar",
  "Omani Rial",
  "Papua New Guinean Kina",
  "Rwandan Franc",
  "Samoan Tala",
  "Serbian Dinar",
  "Swedish Krona",
  "Tanzanian Shilling",
  "Armenian Dram",
  "Bahamian Dollar",
  "Bosnia And Herzegovina Konvertibilna Marka",
  "Cape Verdean Escudo",
  "Chinese Yuan",
  "Costa Rican Colon",
  "Czech Koruna",
  "Eritrean Nakfa",
  "Georgian Lari",
  "Haitian Gourde",
  "Indian Rupee",
  "Jordanian Dinar",
  "South Korean Won",
  "Lebanese Lira",
  "Malawian Kwacha",
  "Mauritanian Ouguiya",
  "Mozambican Metical",
  "Netherlands Antillean Gulden",
  "Peruvian Nuevo Sol",
  "Qatari Riyal",
  "Sao Tome And Principe Dobra",
  "Sierra Leonean Leone",
  "Somali Shilling",
  "Sudanese Pound",
  "Syrian Pound",
  "Angolan Kwanza",
  "Aruban Florin",
  "Bahraini Dinar",
  "Belize Dollar",
  "Botswana Pula",
  "Burundi Franc",
  "Cayman Islands Dollar",
  "Colombian Peso",
  "Danish Krone",
  "Guatemalan Quetzal",
  "Honduran Lempira",
  "Indonesian Rupiah",
  "Israeli New Sheqel",
  "Kazakhstani Tenge",
  "Kuwaiti Dinar",
  "Lesotho Loti",
  "Malaysian Ringgit",
  "Mauritian Rupee",
  "Mongolian Tugrik",
  "Myanma Kyat",
  "Nigerian Naira",
  "Panamanian Balboa",
  "Philippine Peso",
  "Romanian Leu",
  "Saudi Riyal",
  "Singapore Dollar",
  "South African Rand",
  "Surinamese Dollar",
  "New Taiwan Dollar",
  "Paanga",
  "Venezuelan Bolivar",
  "Algerian Dinar",
  "Argentine Peso",
  "Azerbaijani Manat",
  "Belarusian Ruble",
  "Bolivian Boliviano",
  "Bulgarian Lev",
  "Canadian Dollar",
  "Chilean Peso",
  "Congolese Franc",
  "Dominican Peso",
  "Fijian Dollar",
  "Gambian Dalasi",
  "Guyanese Dollar",
  "Icelandic Króna",
  "Iraqi Dinar",
  "Japanese Yen",
  "North Korean Won",
  "Latvian Lats",
  "Swiss Franc",
  "Malagasy Ariary",
  "Moldovan Leu",
  "Moroccan Dirham",
  "Nepalese Rupee",
  "Nicaraguan Cordoba",
  "Pakistani Rupee",
  "Paraguayan Guarani",
  "Saint Helena Pound",
  "Seychellois Rupee",
  "Solomon Islands Dollar",
  "Sri Lankan Rupee",
  "Thai Baht",
  "Turkish New Lira",
  "UAE Dirham",
  "Vanuatu Vatu",
  "Yemeni Rial",
  "Afghan Afghani",
  "Bangladeshi Taka",
  "Brazilian Real",
  "Cambodian Riel",
  "Comorian Franc",
  "Croatian Kuna",
  "Djiboutian Franc",
  "Egyptian Pound",
  "Ethiopian Birr",
  "CFP Franc",
  "Ghanaian Cedi",
  "Guinean Franc",
  "Hong Kong Dollar",
  "Special Drawing Rights",
  "Kenyan Shilling",
  "Kyrgyzstani Som",
  "Liberian Dollar",
  "Macanese Pataca",
  "Maldivian Rufiyaa",
  "Mexican Peso",
  "Namibian Dollar",
  "Norwegian Krone",
  "Polish Zloty",
  "Russian Ruble",
  "Swazi Lilangeni",
  "Tajikistani Somoni",
  "Trinidad and Tobago Dollar",
  "Ugandan Shilling",
  "Uruguayan Peso",
  "Vietnamese Dong",
  "Tunisian Dinar",
  "Ukrainian Hryvnia",
  "Uzbekistani Som",
  "Turkmenistan Manat",
  "British Pound",
  "Zambian Kwacha",
  "Bitcoin",
  "New Belarusian Ruble",
  "Bermudan Dollar",
  "Guernsey Pound",
  "Chilean Unit Of Account",
  "Cuban Convertible Peso",
  "Manx pound",
  "Jersey Pound",
  "Salvadoran Colón",
  "Old Zambian Kwacha",
  "Silver (troy ounce)",
  "Zimbabwean Dollar",
];
